const list = [
  'James',
  'John',
  'Robert',
  'Michael',
  'William',
  'David',
  'Richard',
  'Joseph',
  'Thomas',
  'Charles',
  'Christopher',
  'Daniel',
  'Matthew',
  'Anthony',
  'Donald',
  'Mark',
  'Paul',
  'Steven',
  'Andrew',
  'Kenneth',
  'Joshua',
  'Kevin',
  'Brian',
  'George',
  'Edward',
  'Ronald',
  'Timothy',
  'Jason',
  'Jeffrey',
  'Ryan',
  'Jacob',
  'Gary',
  'Nicholas',
  'Eric',
  'Jonathan',
  'Stephen',
  'Larry',
  'Justin',
  'Scott',
  'Brandon',
  'Benjamin',
  'Samuel',
  'Frank',
  'Gregory',
  'Raymond',
  'Alexander',
  'Patrick',
  'Jack',
  'Dennis',
  'Jerry',
  'Tyler',
  'Aaron',
  'Jose',
  'Henry',
  'Adam',
  'Douglas',
  'Nathan',
  'Peter',
  'Zachary',
  'Kyle',
  'Walter',
  'Harold',
  'Jeremy',
  'Ethan',
  'Carl',
  'Keith',
  'Roger',
  'Gerald',
  'Christian',
  'Terry',
  'Sean',
  'Arthur',
  'Austin',
  'Noah',
  'Lawrence',
  'Jesse',
  'Joe',
  'Bryan',
  'Billy',
  'Jordan',
  'Albert',
  'Dylan',
  'Bruce',
  'Willie',
  'Gabriel',
  'Alan',
  'Juan',
  'Logan',
  'Wayne',
  'Ralph',
  'Roy',
  'Eugene',
  'Randy',
  'Vincent',
  'Russell',
  'Louis',
  'Philip',
  'Bobby',
  'Johnny',
  'Bradley',
  'Females',
  'Mary',
  'Patricia',
  'Jennifer',
  'Linda',
  'Elizabeth',
  'Barbara',
  'Susan',
  'Jessica',
  'Sarah',
  'Karen',
  'Nancy',
  'Lisa',
  'Margaret',
  'Betty',
  'Sandra',
  'Ashley',
  'Dorothy',
  'Kimberly',
  'Emily',
  'Donna',
  'Michelle',
  'Carol',
  'Amanda',
  'Melissa',
  'Deborah',
  'Stephanie',
  'Rebecca',
  'Laura',
  'Sharon',
  'Cynthia',
  'Kathleen',
  'Amy',
  'Shirley',
  'Angela',
  'Helen',
  'Anna',
  'Brenda',
  'Pamela',
  'Nicole',
  'Samantha',
  'Katherine',
  'Emma',
  'Ruth',
  'Christine',
  'Catherine',
  'Debra',
  'Rachel',
  'Carolyn',
  'Janet',
  'Virginia',
  'Maria',
  'Heather',
  'Diane',
  'Julie',
  'Joyce',
  'Victoria',
  'Kelly',
  'Christina',
  'Lauren',
  'Joan',
  'Evelyn',
  'Olivia',
  'Judith',
  'Megan',
  'Cheryl',
  'Martha',
  'Andrea',
  'Frances',
  'Hannah',
  'Jacqueline',
  'Ann',
  'Gloria',
  'Jean',
  'Kathryn',
  'Alice',
  'Teresa',
  'Sara',
  'Janice',
  'Doris',
  'Madison',
  'Julia',
  'Grace',
  'Judy',
  'Abigail',
  'Marie',
  'Denise',
  'Beverly',
  'Amber',
  'Theresa',
  'Marilyn',
  'Danielle',
  'Diana',
  'Brittany',
  'Natalie',
  'Sophia',
  'Rose',
  'Isabella',
  'Alexis',
  'Kayla',
  'Charlotte',
  'Santiago',
  'Daniel',
  'Enzo',
  'Gabriel',
  'José',
  'Noah',
  'William',
  'Agustín',
  'Santiago',
  'Malik',
  'Jayden',
  'Santiago',
  'Ramón',
  'Luis',
  'Sebastián',
  'Liam',
  'James',
  'Agustín',
  'Sebastián',
  'Sofía',
  'Alysha',
  'Maria',
  'Eduarda',
  'Maria',
  'Olivia',
  'Emma',
  'Sofía',
  'Mariana',
  'Ivaana',
  'Widelene',
  'Gabrielle',
  'Ximena',
  'María',
  'María',
  'Valentina',
  'Emma',
  'Mary',
  'Florencia',
  'Camila',
  'Madonna',
  'Catherine Zeta-Jones',
  'Renée Zellweger',
  'Burt Young',
  'Gig Young',
  'Loretta Young',
  'Roland Young',
  'Susannah York',
  'Diana Wynyard',
  'Ed Wynn',
  'Jane Wyman',
  'Margaret Wycherly',
  'Teresa Wright',
  'Monty Woolley',
  'Joanne Woodward',
  'James Woods',
  'Alfre Woodard',
  'Natalie Wood',
  'Peggy Wood',
  'Reese Witherspoon',
  'Shelley Winters',
  'Kate Winslet',
  'Mare Winningham',
  'Debra Winger',
  'Oprah Winfrey',
  'Paul Winfield',
  'Chill Wills',
  'Cara Williams',
  'Michelle Williams',
  'Robin Williams',
  'Tom Wilkinson',
  'Gene Wilder',
  'Cornel Wilde',
  'Jack Wild',
  'Dianne Wiest',
  'Richard Widmark',
  'May Whitty',
  'James Whitmore',
  'Stuart Whitman',
  'Forest Whitaker',
  'Oskar Werner',
  'Orson Welles',
  'Tuesday Weld',
  'Rachel Weisz',
  'Clifton Webb',
  'Jacki Weaver',
  'Sigourney Weaver',
  'John Wayne',
  'Naomi Watts',
  'Emily Watson',
  'Lucile Watson',
  'Sam Waterston',
  'Ethel Waters',
  'Ken Watanabe',
  'Denzel Washington',
  'Lesley Ann Warren',
  'H. B. Warner',
  'Jack Warden',
  'Christoph Waltz',
  'Julie Walters',
  'Quvenzhané Wallis',
  'Christopher Walken',
  'Mark Wahlberg',
  'Max von Sydow',
  'Jon Voight',
  'Alicia Vikander',
  'Robert Vaughn',
  'Diane Varsi',
  'Jo Van Fleet',
  'Brenda Vaccaro',
  'Peter Ustinov',
  'Mary Ure',
  'Miyoshi Umeki',
  'Liv Ullmann',
  'Cicely Tyson',
  'Susan Tyrrell',
  'Kathleen Turner',
  'Lana Turner',
  'Tom Tully',
  'Stanley Tucci',
  'Massimo Troisi',
  'Claire Trevor',
  'John Travolta',
  'Henry Travers',
  'Lee Tracy',
  'Spencer Tracy',
  'Rip Torn',
  'Topol',
  'Franchot Tone',
  'Lily Tomlin',
  'Marisa Tomei',
  'Richard Todd',
  'Jennifer Tilly',
  'Meg Tilly',
  'Gene Tierney',
  'Lawrence Tibbett',
  'Uma Thurman',
  'Billy Bob Thornton',
  'Emma Thompson',
  'Charlize Theron',
  'Elizabeth Taylor',
  'Jessica Tandy',
  'Akim Tamiroff',
  'Russ Tamblyn',
  'Tilda Swinton',
  'Gloria Swanson',
  'Hilary Swank',
  'Janet Suzman',
  'Margaret Sullavan',
  'Gloria Stuart',
  'Erich von Stroheim',
  'Barbra Streisand',
  'Meryl Streep',
  'Robert Strauss',
  'David Strathairn',
  'Lee Strasberg',
  'Beatrice Straight',
  'Emma Stone',
  'Lewis Stone',
  'Sharon Stone',
  'Dean Stockwell',
  'James Stewart',
  'Jan Sterling',
  'James Stephenson',
  'Hailee Steinfeld',
  'Rod Steiger',
  'Mary Steenburgen',
  'Imelda Staunton',
  'Maureen Stapleton',
  'Barbara Stanwyck',
  'Kim Stanley',
  'Terence Stamp',
  'Sylvester Stallone',
  'Robert Stack',
  'June Squibb',
  'Octavia Spencer',
  'Kevin Spacey',
  'Sissy Spacek',
  'Ann Sothern',
  'Mira Sorvino',
  'Gale Sondergaard',
  'Carrie Snodgress',
  'Maggie Smith',
  'Will Smith',
  'Lilia Skala',
  'Gary Sinise',
  'Frank Sinatra',
  'J. K. Simmons',
  'Jean Simmons',
  'Simone Signoret',
  'Sylvia Sidney',
  'Gabourey Sidibe',
  'Elisabeth Shue',
  'Anne Shirley',
  'Talia Shire',
  'Sam Shepard',
  'Norma Shearer',
  'Robert Shaw',
  'Omar Sharif',
  'Michael Shannon',
  'Chloë Sevigny',
  'Peter Sellers',
  'George Segal',
  'Kristin Scott Thomas',
  'George C. Scott §',
  'Martha Scott',
  'Paul Scofield',
  'Joseph Schildkraut',
  'Maximilian Schell',
  'Roy Scheider',
  'Diana Scarwid',
  'Telly Savalas',
  'Chris Sarandon',
  'Susan Sarandon',
  'Catalina Sandino Moreno',
  'George Sanders',
  'Eva Marie Saint',
  'Mark Rylance',
  'Winona Ryder',
  'Amy Ryan',
  'Robert Ryan',
  'Margaret Rutherford',
  'Harold Russell',
  'Rosalind Russell',
  'Geoffrey Rush',
  'Mark Ruffalo',
  'Mercedes Ruehl',
  'Gena Rowlands',
  'Mickey Rourke',
  'Tim Roth',
  'Diana Ross',
  'Katharine Ross',
  'Mickey Rooney',
  'Saoirse Ronan',
  'Howard Rollins',
  'Ginger Rogers',
  'Sam Rockwell',
  'Flora Robson',
  'May Robson',
  'Cliff Robertson',
  'Eric Roberts',
  'Julia Roberts',
  'Rachel Roberts',
  'Tim Robbins',
  'Margot Robbie',
  'Jason Robards',
  'Emmanuelle Riva',
  'Thelma Ritter',
  'Miranda Richardson',
  'Ralph Richardson',
  'Beah Richards',
  'Burt Reynolds',
  'Debbie Reynolds',
  'Anne Revere',
  'Jeremy Renner',
  'Lee Remick',
  'John C. Reilly',
  'Donna Reed',
  'Eddie Redmayne',
  'Joyce Redman',
  'Lynn Redgrave',
  'Michael Redgrave',
  'Vanessa Redgrave',
  'Robert Redford',
  'Stephen Rea',
  'Basil Rathbone',
  'Anne Ramsey',
  'Charlotte Rampling',
  'Marjorie Rambeau',
  'Claude Rains',
  'Luise Rainer',
  'Anthony Quinn',
  'Kathleen Quinlan',
  'Anthony Quayle',
  'Randy Quaid',
  'Florence Pugh',
  'Jonathan Pryce',
  'Robert Preston',
  'William Powell',
  'Pete Postlethwaite',
  'Natalie Portman',
  'Michael J. Pollard',
  'Sidney Poitier',
  'Christopher Plummer',
  'Joan Plowright',
  'Brad Pitt',
  'Rosamund Pike',
  'Walter Pidgeon',
  'Mary Pickford',
  'Joaquin Phoenix',
  'River Phoenix',
  'Michelle Pfeiffer',
  'Susan Peters',
  'Joe Pesci',
  'Valerie Perrine',
  'Anthony Perkins',
  'Rosie Perez',
  'Sean Penn',
  'Gregory Peck',
  'David Paymer',
  'Katina Paxinou',
  'Marisa Pavan',
  'Dev Patel',
  'Estelle Parsons',
  'Larry Parks',
  'Eleanor Parker',
  'Anna Paquin',
  'Gwyneth Paltrow',
  'Chazz Palminteri',
  'Jack Palance',
  'Ellen Page',
  'Geraldine Page',
  'Al Pacino',
  'Clive Owen',
  'Maria Ouspenskaya',
  'Haley Joel Osment',
  'Nancy Olson',
  'Edward James Olmos',
  'Laurence Olivier',
  'Edna May Oliver',
  'Lena Olin',
  'Gary Oldman',
  'Sophie Okonedo',
  'Merle Oberon',
  'Jack Oakie',
  'Edward Norton',
  'Nick Nolte',
  'David Niven',
  'Jack Nicholson',
  'Haing S. Ngor',
  'Paul Newman',
  'Kate Nelligan',
  'Ruth Negga',
  'Liam Neeson',
  'Patricia Neal',
  'Mildred Natwick',
  'J. Carrol Naish',
  'Bill Murray',
  'Don Murray',
  'Eddie Murphy',
  'Paul Muni',
  'Carey Mulligan',
  'Armin Mueller-Stahl',
  'Samantha Morton',
  'Viggo Mortensen',
  'Chester Morris',
  'Robert Morley',
  'Pat Morita',
  'Cathy Moriarty',
  'Frank Morgan',
  'Rita Moreno',
  'Agnes Moorehead',
  'Dudley Moore',
  'Grace Moore',
  'Juanita Moore',
  'Julianne Moore',
  'Mary Tyler Moore',
  'Terry Moore',
  'Ron Moody',
  'Robert Montgomery',
  'Fernanda Montenegro',
  "Mo'Nique",
  'Robert Mitchum',
  'Thomas Mitchell',
  'Helen Mirren',
  'Liza Minnelli',
  'Sal Mineo',
  'John Mills',
  'Jason Miller',
  'Ray Milland',
  'Penelope Milford',
  'Sarah Miles',
  'Sylvia Miles',
  'Bette Midler',
  'Laurie Metcalf',
  'Una Merkel',
  'Burgess Meredith',
  'Melina Mercouri',
  'Vivien Merchant',
  'Adolphe Menjou',
  'Kay Medford',
  'Janet McTeer',
  'Steve McQueen',
  'Maggie McNamara',
  'Victor McLaglen',
  'Ian McKellen',
  'Dorothy McGuire',
  'Elizabeth McGovern',
  'Frances McDormand',
  'Mary McDonnell',
  'Hattie McDaniel',
  'Patty McCormack',
  'Matthew McConaughey',
  'Kevin McCarthy',
  'Melissa McCarthy',
  'Mercedes McCambridge',
  'Rachel McAdams',
  'Walter Matthau',
  'Marlee Matlin',
  'Marcello Mastroianni',
  'Mary E. Mastrantonio',
  'Daniel Massey',
  'Raymond Massey',
  'James Mason',
  'Marsha Mason',
  'Lee Marvin',
  'John Marley',
  'Colette Marchand',
  'Fredric March',
  'Rooney Mara',
  'Lesley Manville',
  'Joe Mantell',
  'Dorothy Malone',
  'John Malkovich',
  'Rami Malek',
  'Karl Malden',
  'Mako',
  'Marjorie Main',
  'Anna Magnani',
  'Virginia Madsen',
  'Amy Madigan',
  'William H. Macy',
  'Aline MacMahon',
  'Shirley MacLaine',
  'Ali MacGraw',
  'Alfred Lunt',
  'Paul Lukas',
  'Bessie Love',
  'Joan Lorring',
  'Sophia Loren',
  'Carole Lombard',
  'Robert Loggia',
  'Gene Lockhart',
  'Sondra Locke',
  'John Lithgow',
  'Laura Linney',
  'Juliette Lewis',
  'Jared Leto',
  'Michael Lerner',
  'Melissa Leo',
  'Lotte Lenya',
  'Jack Lemmon',
  'Margaret Leighton',
  'Janet Leigh',
  'Jennifer Jason Leigh',
  'Vivien Leigh',
  'Andrea Leeds',
  'Peggy Lee',
  'Heath Ledger',
  'Cloris Leachman',
  'Eva Le Gallienne',
  'Jennifer Lawrence',
  'Jude Law',
  'Piper Laurie',
  'Charles Laughton',
  'Queen Latifah',
  'Brie Larson',
  'Angela Lansbury',
  'Frank Langella',
  'Hope Lange',
  'Jessica Lange',
  'Diane Lane',
  'Martin Landau',
  'Elsa Lanchester',
  'Burt Lancaster',
  'Christine Lahti',
  'Jocelyne LaGarde',
  'Diane Ladd',
  'Jack Kruschen',
  'Miliza Korjus',
  'Susan Kohner',
  'Alexander Knox',
  'Keira Knightley',
  'Shirley Knight',
  'Kevin Kline',
  'Sally Kirkland',
  'Greg Kinnear',
  'Ben Kingsley',
  'Regina King',
  'Rinko Kikuchi',
  'Nicole Kidman',
  'Deborah Kerr',
  'Arthur Kennedy',
  'George Kennedy',
  'Anna Kendrick',
  'Gene Kelly',
  'Grace Kelly',
  'Nancy Kelly',
  'Sally Kellerman',
  'Cecil Kellaway',
  'Harvey Keitel',
  'Catherine Keener',
  'Lila Kedrova',
  'Diane Keaton',
  'Michael Keaton',
  'Carol Kane',
  'Ida Kamińska',
  'Daniel Kaluuya',
  'Madeline Kahn',
  'Katy Jurado',
  'Carolyn Jones',
  'Felicity Jones',
  'James Earl Jones',
  'Jennifer Jones',
  'Shirley Jones',
  'Tommy Lee Jones',
  'Angelina Jolie',
  'Ben Johnson',
  'Celia Johnson',
  'Glynis Johns',
  'Scarlett Johansson',
  'Richard Jenkins',
  'Marianne Jean-Baptiste',
  'Emil Jannings',
  'Allison Janney',
  'Dean Jagger',
  'Sam Jaffe',
  'Richard Jaeckel',
  'Glenda Jackson',
  'Samuel L. Jackson',
  'Hugh Jackman',
  'Burl Ives',
  'Amy Irving',
  'Jeremy Irons',
  'John Ireland',
  'Martha Hyer',
  'Timothy Hutton',
  'Anjelica Huston',
  'John Huston',
  'Walter Huston',
  'Ruth Hussey',
  'John Hurt',
  'William Hurt',
  'Isabelle Huppert',
  'Holly Hunter',
  'Kim Hunter',
  'Helen Hunt',
  'Linda Hunt',
  'Arthur Hunnicutt',
  'Josephine Hull',
  'Tom Hulce',
  'Felicity Huffman',
  'Jennifer Hudson',
  'Kate Hudson',
  'Rock Hudson',
  'Leslie Howard',
  'Terrence Howard',
  'Trevor Howard',
  'John Houseman',
  'Djimon Hounsou',
  'Bob Hoskins',
  'Dennis Hopper',
  'Anthony Hopkins',
  'Miriam Hopkins',
  'Oskar Homolka',
  'Celeste Holm',
  'Ian Holm',
  'Stanley Holloway',
  'Judy Holliday',
  'William Holden',
  'Hal Holbrook',
  'Dustin Hoffman',
  'Philip Seymour Hoffman',
  'Judd Hirsch',
  'Wendy Hiller',
  'Jonah Hill',
  'William Hickey',
  'Charlton Heston',
  'Barbara Hershey',
  'Audrey Hepburn',
  'Katharine Hepburn',
  'Taraji P. Henson',
  'Justin Henry',
  'Mariel Hemingway',
  'Van Heflin',
  'Lucas Hedges',
  'Eileen Heckart',
  'Susan Hayward',
  'Helen Hayes',
  'Salma Hayek',
  'Sessue Hayakawa',
  'Nigel Hawthorne',
  'Goldie Hawn',
  'Sally Hawkins',
  'John Hawkes',
  'Ethan Hawke',
  'Anne Hathaway',
  'Laurence Harvey',
  'Elizabeth Hartman',
  'Rex Harrison',
  'John F. Kennedy',
  'Barbara Harris',
  'Ed Harris',
  'Julie Harris',
  'Naomie Harris',
  'Richard Harris',
  'Rosemary Harris',
  'Woody Harrelson',
  'Tess Harper',
  'Tom Hardy',
  'Ann Harding',
  'Marcia Gay Harden',
  'Tom Hanks',
  'Grayson Hall',
  'Jackie Earle Haley',
  'Jean Hagen',
  'Gene Hackman',
  'Joan Hackett',
  'Jake Gyllenhaal',
  'Maggie Gyllenhaal',
  'Edmund Gwenn',
  'Alec Guinness',
  'Rachel Griffiths',
  'Corinne Griffith',
  'Hugh Griffith',
  'Melanie Griffith',
  'Joel Grey',
  'Sydney Greenstreet',
  'Graham Greene',
  'Bonita Granville',
  'Cary Grant',
  'Lee Grant',
  'Richard E. Grant',
  'Gloria Grahame',
  'Elliott Gould',
  'Louis Gossett Jr.',
  'Ryan Gosling',
  'Dexter Gordon',
  'Ruth Gordon',
  'Cuba Gooding Jr.',
  'Thomas Gomez',
  'Whoopi Goldberg',
  'Paulette Goddard',
  'Jackie Gleason',
  'James Gleason',
  'Lillian Gish',
  'Jack Gilford',
  'John Gielgud',
  'Giancarlo Giannini',
  'Paul Giamatti',
  'Chief Dan George',
  'Gladys George',
  'Leo Genn',
  'Michael V. Gazzo',
  'Janet Gaynor',
  'Greer Garson',
  'Teri Garr',
  'James Garner',
  'Judy Garland',
  'William Gargan',
  'Andrew Garfield',
  'John Garfield',
  'Ava Gardner',
  'Vincent Gardenia',
  'Andy García',
  'Greta Garbo',
  'Lady Gaga',
  'Clark Gable',
  'Brenda Fricker',
  'Leonard Frey',
  'Morgan Freeman',
  'James Franco',
  'Anthony Franciosa',
  'Jamie Foxx',
  'Jodie Foster',
  'Robert Forster',
  'Frederic Forrest',
  'Harrison Ford',
  'Lynn Fontanne',
  'Joan Fontaine',
  'Henry Fonda',
  'Jane Fonda',
  'Peter Fonda',
  'Nina Foch',
  'Louise Fletcher',
  'Barry Fitzgerald',
  'Geraldine Fitzgerald',
  'Laurence Fishburne',
  'Colin Firth',
  'Peter Firth',
  'Albert Finney',
  'Frank Finlay',
  'Peter Finch',
  'Ralph Fiennes',
  'Sally Field',
  'José Ferrer',
  'Michael Fassbender',
  'Richard Farnsworth',
  'Vera Farmiga',
  'Peter Falk',
  'Edith Evans',
  'Stuart Erwin',
  'Cynthia Erivo',
  'Hope Emerson',
  'Denholm Elliott',
  'Sam Elliott',
  'Chiwetel Ejiofor',
  'Jesse Eisenberg',
  'Samantha Eggar',
  'Clint Eastwood',
  'Jeanne Eagels',
  'Robert Duvall',
  'Charles Durning',
  'Mildred Dunnock',
  'Irene Dunne',
  'James Dunn',
  'Michael Dunn',
  'Michael Clarke Duncan',
  'Faye Dunaway',
  'Patty Duke',
  'Olympia Dukakis',
  'Jean Dujardin',
  'Adam Driver',
  'Minnie Driver',
  'Richard Dreyfuss',
  'Marie Dressler',
  'Louise Dresser',
  'Robert Downey Jr.',
  'Brad Dourif',
  'Kirk Douglas',
  'Melvyn Douglas',
  'Michael Douglas',
  'Brian Donlevy',
  'Robert Donat',
  'Richard Dix',
  'Matt Dillon',
  'Melinda Dillon',
  'Marlene Dietrich',
  'Leonardo DiCaprio',
  'Brandon deWilde',
  'Bruce Dern',
  'Laura Dern',
  'Johnny Depp',
  'Gérard Depardieu',
  'Sandy Dennis',
  'Catherine Deneuve',
  'Judi Dench',
  'William Demarest',
  'Benicio del Toro',
  'Ruby Dee',
  'James Dean',
  'Marina de Tavira',
  'Vittorio De Sica',
  'Robert De Niro',
  'Olivia de Havilland',
  'Daniel Day-Lewis',
  'Doris Day',
  'Bruce Davison',
  'Bette Davis',
  'Geena Davis',
  'Judy Davis',
  'Viola Davis',
  'Jaye Davidson',
  'Jane Darwell',
  'Bobby Darin',
  'Dorothy Dandridge',
  'Matt Damon',
  'John Dall',
  'Dan Dailey',
  'Willem Dafoe',
  'Joan Cusack',
  'Tony Curtis',
  'Quinn Cummings',
  'Benedict Cumberbatch',
  'Penélope Cruz',
  'Tom Cruise',
  'Russell Crowe',
  'Lindsay Crouse',
  'Rupert Crosse',
  'Bing Crosby',
  'Hume Cronyn',
  'James Cromwell',
  'Donald Crisp',
  'Broderick Crawford',
  'Joan Crawford',
  'Bryan Cranston',
  'Jeanne Crain',
  'Tom Courtenay',
  'Marion Cotillard',
  'Kevin Costner',
  'Valentina Cortese',
  'Ellen Corby',
  'Bradley Cooper',
  'Chris Cooper',
  'Gary Cooper',
  'Gladys Cooper',
  'Jackie Cooper',
  'Tom Conti',
  'Sean Connery',
  'Jennifer Connelly',
  'Betty Compson',
  'Olivia Colman',
  'Ronald Colman',
  'Pauline Collins',
  'Patricia Collinge',
  'Toni Collette',
  'Claudette Colbert',
  'James Coco',
  'Charles Coburn',
  'James Coburn',
  'Lee J. Cobb',
  'Glenn Close',
  'George Clooney',
  'Montgomery Clift',
  'Jill Clayburgh',
  'Patricia Clarkson',
  'Candy Clark',
  'Diane Cilento',
  'Thomas Haden Church',
  'Julie Christie',
  'Maurice Chevalier',
  'Cher',
  'Michael Chekhov',
  'Don Cheadle',
  'Ruth Chatterton',
  'Jessica Chastain',
  'Charlie Chaplin',
  'Carol Channing',
  'Stockard Channing',
  'Jeff Chandler',
  'Timothée Chalamet',
  'George Chakiris',
  'Keisha Castle-Hughes',
  'Richard S. Castellano',
  'Seymour Cassel',
  'John Cassavetes',
  'Peggy Cass',
  'Diahann Carroll',
  'Nancy Carroll',
  'Leslie Caron',
  'Art Carney',
  'Lynn Carlin',
  'Harry Carey',
  'Steve Carell',
  'Dyan Cannon',
  'Louis Calhern',
  'Michael Caine',
  'James Cagney',
  'Nicolas Cage',
  'Adolph Caesar',
  'James Caan',
  'Spring Byington',
  'Red Buttons',
  'Gary Busey',
  'Richard Burton',
  'Ellen Burstyn',
  'Catherine Burns',
  'George Burns',
  'Billie Burke',
  'Victor Buono',
  'Sandra Bullock',
  'Geneviève Bujold',
  'Yul Brynner',
  'Leslie Browne',
  'Albert Brooks',
  'Josh Brolin',
  'Adrien Brody',
  'Jim Broadbent',
  'Jeff Bridges',
  'Abigail Breslin',
  'Eileen Brennan',
  'Walter Brennan',
  'Marlon Brando',
  'Klaus Maria Brandauer',
  'Kenneth Branagh',
  'Alice Brady',
  'Lorraine Bracco',
  'Charles Boyer',
  'Ernest Borgnine',
  'Shirley Booth',
  'Helena Bonham Carter',
  'Beulah Bondi',
  'Humphrey Bogart',
  'Ann Blyth',
  'Joan Blondell',
  'Mary J. Blige',
  'Brenda Blethyn',
  'Cate Blanchett',
  'Ronee Blakley',
  'Betsy Blair',
  'Linda Blair',
  'Karen Black',
  'Juliette Binoche',
  'Theodore Bikel',
  'Charles Bickford',
  'Demián Bichir',
  'Halle Berry',
  'Jeannie Berlin',
  'Elisabeth Bergner',
  'Ingrid Bergman',
  'Candice Bergen',
  'Tom Berenger',
  'Annette Bening',
  'Roberto Benigni',
  'William Bendix',
  'Ralph Bellamy',
  'Barbara Bel Geddes',
  'Bérénice Bejo',
  'Ed Begley',
  'Wallace Beery',
  'Ned Beatty',
  'Warren Beatty',
  'Anne Baxter',
  'Warner Baxter',
  'Alan Bates',
  'Kathy Bates',
  'Angela Bassett',
  'Albert Bassermann',
  'Kim Basinger',
  'Mikhail Baryshnikov',
  'Richard Barthelmess',
  'Ethel Barrymore',
  'Lionel Barrymore',
  'Barbara Barrie',
  'Adriana Barraza',
  'Marie-Christine Barrault',
  'Javier Bardem',
  'Ian Bannen',
  'Antonio Banderas',
  'Anne Bancroft',
  'George Bancroft',
  'Martin Balsam',
  'Christian Bale',
  'Alec Baldwin',
  'Carroll Baker',
  'Fay Bainter',
  'Mary Badham',
  'Hermione Baddeley',
  'Lauren Bacall',
  'Lew Ayres',
  'Dan Aykroyd',
  'Margaret Avery',
  'Mischa Auer',
  'Mary Astor',
  'Fred Astaire',
  'Peggy Ashcroft',
  'Jean Arthur',
  'Patricia Arquette',
  'George Arliss',
  'Alan Arkin',
  'Eve Arden',
  'Anne Archer',
  'Yalitza Aparicio',
  'Ann-Margret',
  'Julie Andrews',
  'Judith Anderson',
  'Don Ameche',
  'Sara Allgood',
  'Joan Allen',
  'Woody Allen',
  'Mahershala Ali',
  'Jane Alexander',
  'Norma Aleandro',
  'Alan Alda',
  'Jack Albertson',
  'Eddie Albert',
  'Anouk Aimée',
  'Danny Aiello',
  'Brian Aherne',
  'Shohreh Aghdashloo',
  'Casey Affleck',
  'Isabelle Adjani',
  'Amy Adams',
  'Nick Adams',
  'F. Murray Abraham',
  'Barkhad Abdi',
  'Winston Churchill',
  'Isambard Kingdom Brunel',
  'Diana, Princess of Wales',
  'Charles Darwin',
  'William Shakespeare',
  'Sir Isaac Newton',
  'Elizabeth I',
  'John Lennon',
  'Vice-Admiral Horatio Nelson',
  'Oliver Cromwell',
  'Jesus',
  'Napoleon',
  'Muhammad',
  'William Shakespeare',
  'Abraham Lincoln',
  'George Washington',
  'Aristotle',
  'Alexander the Great',
  'Thomas Jefferson',
  'Henry VIII of England',
  'Charles Darwin',
  'Elizabeth I of England',
  'Karl Marx',
  'Julius Caesar',
  'Queen Victoria',
  'Martin Luther',
  'Joseph Stalin',
  'Albert Einstein',
  'Christopher Columbus',
  'Isaac Newton',
  'Charlemagne',
  'Theodore Roosevelt',
  'Wolfgang Amadeus Mozart',
  'Plato',
  'Louis XIV of France',
  'Ludwig van Beethoven',
  'Ulysses S. Grant',
  'Leonardo da Vinci',
  'Augustus',
  'Carl Linnaeus',
  'Ronald Reagan',
  'Charles Dickens',
  'Paul the Apostle',
  'Benjamin Franklin',
  'George W. Bush',
  'Winston Churchill',
  'Genghis Khan',
  'Charles I of England',
  'Thomas Edison',
  'James I of England',
  'Friedrich Nietzsche',
  'Franklin D. Roosevelt',
  'Sigmund Freud',
  'Alexander Hamilton',
  'Mohandas Karamchand Gandhi',
  'Woodrow Wilson',
  'Johann Sebastian Bach',
  'Galileo Galilei',
  'James Madison',
  'Gautama Buddha',
  'Mark Twain',
  'Edgar Allan Poe',
  'Joseph Smith, Jr.',
  'Adam Smith',
  'David, King of Israel',
  'George III of the United Kingdom',
  'Immanuel Kant',
  'James Cook',
  'John Adams',
  'Richard Wagner',
  'Pyotr Ilyich Tchaikovsky',
  'Voltaire',
  'Saint Peter',
  'Andrew Jackson',
  'Constantine the Great',
  'Socrates',
  'Elvis Presley',
  'William the Conqueror',
  'John F. Kennedy',
  'Augustine of Hippo',
  'Vincent van Gogh',
  'Nicolaus Copernicus',
  'Vladimir Lenin',
  'Robert E. Lee',
  'Oscar Wilde',
  'Charles II of England',
  'Cicero',
  'Jean-Jacques Rousseau',
  'Francis Bacon',
  'Richard Nixon',
  'Louis XVI of France',
  'Charles V, Holy Roman Emperor',
  'King Arthur',
  'Michelangelo',
  'Philip II of Spain',
  'Johann Wolfgang von Goethe',
  'Ali',
  'Zhou Enlai',
  'Oda Nobunaga',
  'Thomas Aquinas',
  'Pope John Paul II',
  'René Descartes',
  'Nikola Tesla',
  'Harry S. Truman',
  'Joan of Arc',
  'Dante Alighieri',
  'Otto von Bismarck',
  'Grover Cleveland',
  'Chimamanda Ngozi Adichie',
  'John Calvin',
  'John Locke',
  'Chen Shui-bian',
  'Li Hongzhang',
  'Sakamoto Ryōma',
  'Kim Jong-Un',
  'Asbel Kiprop',
  'Akbar the Great',
  'Lin Siniang',
  'Ching Shih',
  'Hua Mulan',
  'Bolo Yeung',
  'Meera Syal',
  'Mansa Musa',
  'Santa Claus',
  'Satan',
  'Abel Magwitch',
  'Abra Bacon',
  'Abraham Van Helsing',
  'Adam Trask',
  'Agnes Wickfield',
  'Captain Ahab',
  'Albus Dumbledore',
  'Alex',
  'Dr Alexandre Manette',
  'Alice',
  'Alice Henderson',
  'Allan Woodcourt',
  'Altamiro',
  'Amelia Sedley',
  'Amy Dorrit',
  'Amy March',
  'Anatole Kuragin',
  'Anatool',
  'André - Louis  Moreau',
  'Prince Andrey Bolkonsky',
  'Anna Karenina',
  'Anne Elliot',
  'Anne Shirley',
  'Anne Steele',
  'Ante',
  'Anton Chigurh',
  'Aragorn II Elessar',
  'Aron Trask',
  'Arthur Dent',
  'Arthur Gride',
  'Arthur Holmwood',
  'Arthur Radley',
  'Arya  Stark',
  'Ashley Wilkes',
  'Atticus Finch',
  'Augusta Elton',
  'Ault Allen',
  'Aureliano Buendia',
  'Azelma Thénardier',
  'Basil Hallward',
  'Bathsheba Everdene',
  'Beatrice Prior',
  'Beauregard Wilkes',
  'Bella Swan',
  'Bellatrix Lestrange',
  'Belle Watling',
  'Ben Pentland',
  'Benjamin Bunny',
  'Benjy Compson',
  'Beowulf',
  'Bernard Marx',
  'Bertha Antoinetta Mason',
  'Beryl Stapleton',
  'Bess Marvin',
  'Betsey Trotwood',
  'Betsy Ray',
  'Bilbo Baggins',
  'Bill Sikes',
  'Billy Pilgrim',
  'Bob Allen',
  'Boes',
  'Bonnie Butler',
  'Bran Stark',
  'Colonel Brandon',
  'Bridget Jones',
  'Bruce Wayne',
  'Little Burl Allen',
  'Caddie Woodlawn',
  'Cain Ball',
  'Caleb Trask',
  'Campion',
  'Campion',
  'Campion Bond',
  'Caroline Bingley',
  "Carreen O'Hara",
  'Catelyn Stark',
  'Catherine Earnshaw',
  'Catherine Bennet',
  'Lady Catherine de Bourgh',
  'Catherine Morland',
  'Cathy Ames',
  'Catootje Tromp',
  'Cecelia Jupe',
  'Cedric Diggory',
  'Cersei Lannister',
  'Charles Bingley',
  'Charles Darnay',
  'Charles Hamilton',
  'Charles Baker  Harris',
  'Charles Musgrove',
  'Charles Trask',
  'Charlie Bucket',
  'Charlotte A. Cavatica',
  'Charlotte Lucas',
  'Chet Morton',
  'Christopher John  Francis  Boone',
  'Christophe Robin',
  'Christy Huddleston',
  'Chuck Cathcart',
  'Clarice Starling',
  'Clarissa Dalloway',
  'Clarissa Harlowe',
  'Clark Kent',
  'Claude Frollo',
  'Claudia',
  'Clopin Trouillefou',
  'Conan the Barbarian',
  'Coraline Jones',
  'Cosette Fauchelevant',
  'Creed Allen',
  'Cthulhu',
  'Cubitus',
  'Cyrus Trask',
  'Daenerys Targaryen',
  'Daisy Buchanan',
  'Daniel Deronda',
  'Dariel',
  'David Balfour',
  'David Copperfield',
  'David Grantland',
  'Dexter Morgan',
  'Diana Barry',
  'Dilsey Gibson',
  'Dolores Umbridge',
  'Dorian Gray',
  'Dorothy Gale',
  'Draco Malfoy',
  'Count Dracula',
  'Khal Drogo',
  'Ebenezer Scrooge',
  'Eddard Stark',
  'Edmond Dantès',
  'Edmund Bertram',
  'Edmund Pevensie',
  'Edred Fitzpiers',
  'Edward Cullen',
  'Edward Ferrars',
  'Edward Fairfax Rochester',
  'Elam Harnish',
  'Eleanor Tilney',
  'Elinor Dashwood',
  'Elizabeth Bennet',
  'Elizabeth Elliot',
  'Elizabeth March',
  'Ella Lorena  Kennedy',
  "Ellen Robillard O'Hara",
  'Ellis Redding',
  'Elrond',
  'Emily Trevelyan',
  'Emma Woodhouse',
  'Éponine Thénardier',
  'Erik',
  'Esmeralda',
  'Estella Havisham',
  'Esther Summerson',
  'Fairlight Spencer',
  'Fanny Dashwood',
  'Fanny Price',
  'Fanny Robin',
  'Fanny Squeers',
  'Fantine',
  'Felicity  King',
  'Felicity Merriman',
  'Fitzwilliam Darcy',
  'Princess Flavia of Ruritania',
  'Florete',
  'Floriant',
  'Ford Prefect',
  'Forrest Gump',
  'Francis Troy',
  'Frank Churchill',
  'Frank Hardy',
  'Frank Kennedy',
  'Frederick Tilney',
  'Lord Frederick Verisopht',
  'Captain Frederick Wentworth',
  'Friedrich Bhaer',
  'Frodo Baggins',
  'Gabriel Oak',
  'Galadriel',
  'Gandalf',
  'Geoffrey  Firmin',
  'George Fayne',
  'George Knightley',
  'George Milton',
  'George Osborne',
  'George Smiley',
  'George Wickham',
  'Georgiana Darcy',
  "Gerald O'Hara",
  'Gerrit Tromp',
  'Gertrude  Morel',
  'Gideon Sarn',
  'Gilbert Blythe',
  'Giles Winterborne',
  'Ginevra Weasley',
  'Gloriant',
  'Goldmund',
  'Gollum',
  'Grace Melbury',
  'Gregor Samsa',
  'Guy Montag',
  'Gwendolen Harleth',
  'Ham Peggotty',
  'Hannibal Lecter',
  'Harriet Smith',
  '"Harry "Rabbit" Angstrom"',
  'Harry  Morgan',
  'Harry Potter',
  'Hazel Grace Lancaster',
  'Hélène Kuragina',
  'Helmholtz Watson',
  'Henrietta Musgrove',
  'Henrietta Petowker',
  'Henry Crawford',
  'Henry Jekyll',
  'Henry Tilney',
  'Henry Woodhouse',
  'Lord Henry Wotton',
  'Herbert Pocket',
  'Hercule Poirot',
  'Hermione Granger',
  'Hester Prynne',
  'Holden Caulfield',
  'Holly Golightly',
  'Honoria, Lady Dedlock',
  'Huckleberry  Finn',
  'Humbert Humbert',
  'Ida Grantland',
  'Ignatius  Reilly',
  'Count Ilya Rostov',
  'India Wilkes',
  'Isabel  Evans',
  'Isabella Knightley',
  'Isabella Thorpe',
  'Isabelle de Merteuil',
  'Jack Dawkins',
  'Jack Torrance',
  'Jacob Marley',
  'Jaime Lannister',
  'James Benwick',
  'James Bond',
  'Professor James  Moriarty',
  'James Morland',
  'Jan Tromp',
  'Jancis Beguildy',
  'Jane Andrews',
  'Jane Bennet',
  'Jane Eyre',
  'Jane Fairfax',
  'Miss Jane Marple',
  'Jane  Porter',
  'Jans Tromp',
  'Jason  Bourne',
  'Jason Compson IV',
  'Inspector Javert',
  'Jay Gatsby',
  'Jean Louise Finch',
  'Jean Valjean',
  'Jeb Spencer',
  'Jemima Puddleduck',
  'Jeremy Atticus Finch',
  'Jeremy Fisher',
  'Jeroentje',
  'Jerom',
  'Jerusha  Abbott',
  'Jessica Rabbit',
  'Jim Valenti',
  'Joe Hardy',
  'Joffrey Baratheon',
  'John the Savage',
  'John Brooke',
  'John Browdie',
  'John Dashwood',
  'John Seward',
  'John Thorpe',
  'Dr. John  Watson',
  'John Willoughby',
  'John Yossarian',
  'Jommeke',
  'Jon Snow',
  'Jonathan Harker',
  'Jonathas',
  'Jordan Baker',
  'Josef K.',
  'Joseph Gargery',
  'Joseph Sedley',
  'Josephine Barry',
  'Josephine March',
  'Josiah Bounderby',
  'Josie Pye',
  'Don Juan',
  'Judah Ben-Hur',
  'Julia Bertram',
  'Julia Ray',
  'Karlijn Tromp',
  'Kate Nickleby',
  'Katniss Everdeen',
  'Kester Woodseaves',
  'Kilgore Trout',
  'Konala',
  'Kyle Valenti',
  'Lemuel Gulliver',
  'Lenina Crowne',
  'Lennie Small',
  'Leopold Bloom',
  'Liesel Meminger',
  'Lily Bart',
  'Princess Lise Bolkonskaya',
  'Loedertje',
  '"Logan "Wolverine""',
  'Lois Lane',
  'Lolita',
  'Lorna Doone',
  'Louis Trevelyan',
  'Louisa Gradgrind',
  'Louisa Musgrove',
  'Lucie Manette',
  'Lucius Malfoy',
  'Lucy Pevensie',
  'Lucy Steele',
  'Lucy Westenra',
  'Luna Lovegood',
  'Lundy Taylor',
  'Lydia Bennet',
  'Lydia Smallbury',
  'Madeline',
  'Madeline Bray',
  'Margaret Dashwood',
  'Margaret March',
  'Margaret Ray',
  'Maria Bertram',
  'Maria DeLuca',
  'Marianne Dashwood',
  'Marilla Cuthbert',
  'Marius Pontmercy',
  'Princess Mariya Bolkonskaya',
  'Marty South',
  'Marv',
  'Mary Allen',
  'Mary Bennet',
  'Mary Crawford',
  'Mary Lennox',
  'Mary Musgrove',
  'Mary Poppins',
  'Maryann Money',
  'Matilda Price',
  'Matthew Cuthbert',
  'Max Evans',
  'Maxim de Winter',
  'Melanie  Hamilton Wilkes',
  'Michael Corleone',
  'Michael Guerin',
  'Mina Harker',
  'Minnie  May Barry',
  'Minthe Guillory',
  'Mirah Lapidoth',
  'Molly Bloom',
  'Moody Spurgeon MacPherson',
  "Mountie O'Teale",
  'Sir Mulberry Hawk',
  'Muriel Stacy',
  'Nancy',
  'Nancy Drew',
  'Narziß',
  'Natasha Rostova',
  'Neil MacNeill',
  'Neville Longbottom',
  'Newman Noggs',
  'Nicholas Nickleby',
  'Nicholas Rubashov',
  'Nick Carraway',
  'Nikolai Rostov',
  'Noah Claypole',
  'Oliver Twist',
  'Othello Guillory',
  'Patrick Bateman',
  'Paul Bäumer',
  'Paul Morel',
  'Pauline Fossil',
  'Peg Sliderskew',
  'Percy  Jackson',
  'Peter Rabbit',
  'Peter Rabbit',
  'Peter Pan',
  'Peter Parker',
  'Peter Pevensie',
  'Petrova Fossil',
  'Petya Rostov',
  'Philip Elton',
  'Philip Pirrip',
  'Phoebus de Chateaupers',
  'Pierre Bezukhov',
  'Pierre Gringoire',
  'Pippi Longstocking',
  'Piscine Molitor Patel',
  'Posy Fossil',
  'Prue Sarn',
  'Quasimodo',
  'Quentin Compson III',
  'Quincey Morris',
  'Don Quixote',
  'Rachel Lynde',
  'Ralph Nickleby',
  'R. P. McMurphy',
  'Rawdon Crawley',
  'Rebecca Sharp',
  'Rhett Butler',
  'Rob Allen',
  'Robb Stark',
  'Robert Baratheon',
  'Robert Ferrars',
  'Robert Langdon',
  'Robinson Crusoe',
  'Roger Rabbit',
  'Ronald Weasley',
  'Rosafiere',
  'Rose Maylie',
  'Rubeus Hagrid',
  'Ruby Gillis',
  'Ruby  Mae  Morrison',
  'Sabrina Spellman',
  'Sam  Houston Holcombe',
  'Samuel Whiskers',
  'Samwise Gamgee',
  'Sancho Panza',
  'Sansa Stark',
  'Santiago',
  'Saruman',
  'Sauron',
  "Scarlett  O'Hara",
  'Sebastian Valmont',
  'Sémaphore',
  'Severus Snape',
  'Sherlock  Holmes',
  'Sibyl Vane',
  'Tante Sidonia',
  'Silas Marner',
  'Sirius  Black',
  'Sonya Rostova',
  'Sophia  Croft',
  'Sophie Neveu',
  'Stephen Blackpool',
  'Stephen Dedalus',
  "Suellen  O'Hara",
  'Susan Pevensie',
  'Suske',
  "Swannie O'Teale",
  'Sydney Carton',
  'Tacy Kelly',
  'Tarzan',
  'Tess Durbeyfield',
  'Theodore Laurence',
  'Thérèse Defarge',
  'Sir Thomas Bertram',
  'Thomas Gradgrind',
  'Thomasina Tittlemouse',
  'Tib Muller',
  'Tirzah Ben-Hur',
  'Tom Bertram',
  'Tom  Buchanan',
  'Tom Joad',
  'Tom  Jones',
  'Tom Kitten',
  'Tom  Sawyer',
  'Tommy Beresford',
  'Tony  Stark',
  'Treebeard',
  'Trillian',
  'Tristram Shandy',
  'Tuppence Beresford',
  'Tyler Durden',
  'Tyrion Lannister',
  'Uriah Heep',
  'Dr. Victor Frankenstein',
  'Viserys Targaryen',
  'Vito Corleone',
  'Lord Voldemort',
  'Wackford Squeers',
  'Wade Hampton Hamilton',
  'Sir Walter  Elliot',
  'Wendy Darling',
  'Wilbur',
  'William Dobbin',
  'William  Elliot',
  'William  Price',
  'Willy Wonka',
  'Winnie -the-Pooh',
  'Winston  Smith',
  'Wiske',
  'Zady Spencer',
  'Zaphod Beeblebrox',
  `Al-Ghazali`,
  `Alain de Benoist`,
  `Alan Turing`,
  `Alan Watts`,
  `Albert Camus`,
  `Albertus Magnus`,
  `Anaximenes`,
  `Aristotle`,
  `Arthur Schopenhauer`,
  `Auguste Comte`,
  `Averroes`,
  `Ayn Rand`,
  `Baruch Spinoza`,
  `Bertrand Russell`,
  `Cesare Beccaria`,
  `Charles Sanders Peirce`,
  `Cometan`,
  `Confucius`,
  `Daniel Dennett`,
  `David Hume`,
  `Democritus`,
  `Diogenes`,
  `Edmund Burke`,
  `Edmund Husserl`,
  `Emile Durkheim`,
  `Emma Goldman`,
  `Epictetus`,
  `Epicurus`,
  `Francis Bacon`,
  `Friedrich Engels`,
  `Friedrich Hayek`,
  `Friedrich Nietzsche`,
  `George Berkeley`,
  `George Herbert Mead`,
  `George Santayana`,
  `Georges Bataille`,
  `Gilles Deleuze`,
  `Giordano Bruno`,
  `Gorgias`,
  `Gottfried Leibniz`,
  `Hannah Arendt`,
  `Henry David Thoreau`,
  `Hildegard Of Bingen`,
  `Hypatia`,
  `Ibn Sina`,
  `Immanuel Kant`,
  `Iris Murdoch`,
  `Jacques Derrida`,
  `Jacques Lacan`,
  `Jean Baudrillard`,
  `Jean Jacques Rousseau`,
  `Jean-Paul Sartre`,
  `Jeremy Bentham`,
  `Jiddu Krishnamurti`,
  `John Dewey`,
  `John Hick`,
  `John Locke`,
  `John Rawls`,
  `John Searle`,
  `John Stuart Mill`,
  `Jonathan Edwards`,
  `Judith Butler`,
  `Julia Kristeva`,
  `Jürgen Habermas`,
  `Karl Barth`,
  `Karl Jaspers`,
  `Karl Marx`,
  `Lao Tzu`,
  `Lucien Goldmann`,
  `Ludwig Wittgenstein`,
  `Marcus Aurelius`,
  `Mario Bunge`,
  `Martha Nussbaum`,
  `Martin Buber`,
  `Martin Heidegger`,
  `Mary Wollstonecraft`,
  `Max Scheler`,
  `Max Stirner`,
  `Meister Eckhart`,
  `Michel Foucault`,
  `Miguel De Unamuno`,
  `Niccolò Machiavelli`,
  `Nick Bostrom`,
  `Noam Chomsky`,
  `Parmenides`,
  `Peter Singer`,
  `Plato`,
  `René Descartes`,
  `Robert Nozick`,
  `Roland Barthes`,
  `Rosa Luxemburg`,
  `Rudolf Steiner`,
  `Seneca`,
  `Sigmund Freud`,
  `Simone De Beauvoir`,
  `Simone Weil`,
  `Socrates`,
  `Sor Juana`,
  `Søren Kierkegaard`,
  `Theodor Adorno`,
  `Thomas Aquinas`,
  `Thomas Hobbes`,
  `Thomas Jefferson`,
  `Thomas Kühn`,
  `U.G. Krishnamurti`,
  `Voltaire`,
  `Walter Benjamin`,
  `Wilhelm Reich`,
  `William James`,
  `William Lane Craig`
];

module.exports = (possessive) => {
  let word = list[Math.floor(Math.random() * list.length)];
  if (possessive) {
    word[word.length - 1] === 's' ? (word = word.concat(`'`)) : (word = word.concat(`'s`));
  }
  return word;
};
