const list = [
  'Tokyo',
  'Delhi',
  'Shanghai',
  'São Paulo',
  'Mexico City',
  'Cairo',
  'Mumbai',
  'Beijing',
  'Dhaka',
  'Osaka',
  'New York City',
  'Karachi',
  'Buenos Aires',
  'Chongqing',
  'Istanbul',
  'Kolkata',
  'Manila',
  'Lagos',
  'Rio de Janeiro',
  'Tianjin',
  'Kinshasa',
  'Guangzhou',
  'Los Angeles',
  'Moscow',
  'Shenzhen',
  'Lahore',
  'Bangalore',
  'Paris',
  'Bogotá',
  'Jakarta',
  'Chennai',
  'Lima',
  'Bangkok',
  'Seoul',
  'Nagoya',
  'Hyderabad',
  'London',
  'Tehran',
  'Chicago',
  'Chengdu',
  'Nanjing',
  'Wuhan',
  'Ho Chi Minh City',
  'Luanda',
  'Ahmedabad',
  'Kuala Lumpur',
  "Xi'an",
  'Hong Kong',
  'Dongguan',
  'Hangzhou',
  'Foshan',
  'Shenyang',
  'Riyadh',
  'Baghdad',
  'Santiago',
  'Surat',
  'Madrid',
  'Suzhou',
  'Pune',
  'Harbin',
  'Houston',
  'Dallas',
  'Toronto',
  'Dar es Salaam',
  'Miami',
  'Belo Horizonte',
  'Singapore',
  'Philadelphia',
  'Atlanta',
  'Fukuoka',
  'Khartoum',
  'Barcelona',
  'Johannesburg',
  'Saint Petersburg',
  'Qingdao',
  'Dalian',
  'Washington, D.C.',
  'Yangon',
  'Alexandria',
  'Jinan',
  'Guadalajara',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  "Côte d'Ivoire",
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'The Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'The Czech Republic',
  'The Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'The Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'The Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar (formerly Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'The Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'The Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'The Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'The Ukraine',
  'The United Arab Emirates',
  'The United Kingdom',
  'The United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

module.exports = () => {
  return list[Math.floor(Math.random() * list.length)];
};
