const list = [
  'after lunch',
  'before lunch',
  'in bed',
  'at length',
  `out of spite`,
  `out of love`,
  `out of jealousy`,
  `out of hatred`,
  `outdoors`,
  `out of curiosity`,
  `out of breath`,
  `for sure`,
  `for once`,
  `for nothing`,
  `for lunch`,
  `for luck`,
  `for instance`,
  `for fun`,
  `for example`,
  `for certain`,
  `for a while`,
  `for some reason`,
  `for a good cause`,
  `for a change`,
  `with official approval`,
  `with abandon`,
  `at work`,
  `at church`,
  `at the altar`,
  `at McDonald's`,
  `at war`,
  `at university`,
  `at the thought of you`,
  `on top of the world`,
  `in the sky`,
  `under the ground`,
  `in the city`,
  `in the country`,
  `at the time of writing`,
  `at the table`,
  `at the same time`,
  `at the risk of sounding stupid`,
  `at the moment`,
  `at the foot of the bed`,
  `on top of a mountain`,
  `at your expense`,
  `at my expense`,
  `at the end of the day`,
  `at the drop of a hat`,
  `at the door`,
  `at the bottom of a well`,
  `in the beginning of time`,
  `at times`,
  `at short notice`,
  `at sea`,
  `at school`,
  `at random`,
  `by my side`,
  `at his request`,
  `at her request`,
  `at once`,
  `at noon`,
  `at night`,
  `at midnight`,
  `at midday`,
  `at least`,
  `at last`,
  `at home`,
  `at high speed`,
  `at first sight`,
  `at breakfast`,
  `at any rate`,
  `on vacation`,
  `on trial`,
  `on the way to school`,
  `on the way home`,
  `all the way home`,
  `on the roof`,
  `on the radio`,
  `on the phone`,
  `on the first day`,
  `on television`,
  `on parade`,
  `on occasion`,
  `on my wedding day`,
  `on my birthday`,
  `on your birthday`,
  `on horseback`,
  `on fire`,
  `on an expedition`,
  `on a train`,
  `on a summer evening`,
  `on a ship`,
  `on a regular basis`,
  `on a plane`,
  `on a motorbike`,
  `on a bus`,
  `on a bicycle`,
  `under the influence`,
  `under pressure`,
  `in vain`,
  `in the nude`,
  `in the news`,
  `in the mountains`,
  `in the end`,
  `in the dark`,
  `in the beginning`,
  `in the air`,
  `in town`,
  `in winter`,
  `in some respects`,
  `in secret`,
  `in public`,
  `in private`,
  `in prison`,
  `in principle`,
  `in person`,
  `in moderation`,
  `in hiding`,
  `in haste`,
  `in good faith`,
  `in front of police officers`,
  `on the moon`,
  `in flames`,
  `out of fear`,
  `in earnest`,
  `in disguise`,
  `in disgrace`,
  `out of curiosity`,
  `in black and white`,
  `in all likelihood`,
  `in all honesty`,
  `in a way`,
  `in a sense`,
  `in a minute`,
  `in a hurry`,
  `in a deep sleep`
];

module.exports = () => {
  return list[Math.floor(Math.random() * list.length)];
};
